### ISSUE TITLE
Maintenance status?

### ISSUE THREAD

**Issue by dominic-p** [phaxio/phaxio-node#16]
I was wondering if this project is still being maintained.

I'm considering switching to Phaxio from Twilio as they are shutting down their fax service. But, it doesn't look like there's been any activity for a little while. Of course, the project could just be stable which is a good thing. :)

**Comment by jnankin** [comment]
Hi Dominic.  Yes, this is the official Phaxio Node SDK and we do maintain it to ensure it is operational and secure.  If you have any specific questions about implementation or the sdk, we'd be happy to chat!  Hit me up at josh@phaxio.com.

Thanks!

**Comment by dominic-p** [comment]
You rock! Thanks for the quick response. It sounds like I found a good place to migrate from Twilio to. :)
